server:
  port:
    9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: circuit-breaker

client:
  comentarios:
    url: http://localhost:8082

resilience4j.circuitbreaker:
  instances:
    comentarios:
      slidingWindowSize: 8 # monitora 8 requisições
      minimumNumberOfCalls: 4 # se 4 falharem, abre circuito
      permittedNumberOfCallsInHalfOpenState: 2 # qtd de chamadas no estado meio aberto
      waitDurationInOpenState: 10000 # tempo para entrar em status Meio Aberto (em milisegundos)
      # slowCallDurationThreshold: 2000 # tempo de request para contabilizar como falha para abrir o Circuit Breaker


